-- AlterTable
ALTER TABLE "Connection" ALTER COLUMN "connectedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "disconnectedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Device" ALTER COLUMN "firstSeenAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "lastSeenAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);
